
# Project
name: 'disaster_conception'
version: '1.0.0'

# Profile
profile: 'bigquery-portfolio'

# Paths
source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"

# Seeds
seeds:
  disaster_conception:
    enabled: true
    schema: seed_data
      
# Models
models:
  disaster_conception:
      # Applies to all files under models/example/
      marts:
          materialized: table
      staging:
          materialized: view
